openapi: 3.0.3
info:
  title: MS - CUSTOMER CK SPINE
  description: Contracts for checkpoint maintenance.
  termsOfService: https://swagger.io/terms/
  contact:
    email: cramosmon@minsait.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
- url: https://develop-api.actinver.com.mx
  description: Servidor de desarrollo
tags:
- name: catalogs
  description: API for Catalogs SPINE
paths:
  /prospects/checkpoint:
    post:
      summary: Maintenance checkpoint
      description: Saves the information of a specific tab in the onboarding process
      tags:
      - checkpoint
      operationId: createOrUpdateCheckpoint
      parameters:
      - in: header
        name: Content-Type
        schema:
          type: string
          example: application/json
        required: true
      - in: header
        name: Authorization
        schema:
          type: string
          example: BEARER EYJHBGCIOIJIUZI1NIISINR5CCI6IKPXVCJ9.EYJZDWIIOIIXMJM0NTY3ODKWIIWIBMFTZSI6IKPVAG4GRG9LIIWIAWF0IJOXNTE2MJM5MDIYFQ.SFLKXWRJSMEKKF2QT4FWPMEJF36POK6YJV_ADQSSW5C
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/checkpointRequest'
            examples:
              identification:
                value:
                  clientId: 1234
                  sectionId: identification-contact
                  accountId: 1234
                  data:
                    identifications:
                    - country: MX
                      identificationType: '1'
                      identificationNumber: ABC1234567
                      expirationDate: 31/12/2028
                  manifestLetter: false
                  telephones:
                  - type: '1'
                    country: MX
                    areaCode: '+52'
                    phone: '55551234'
                    extension: '123'
                    notificationPhone: true
                  emails:
                  - emailAddress: JUAN.PEREZ@CORREO.COM
                    notificationEmail: true
              initial-data:
                value:
                  clientId: 1234
                  sectionId: initial-data
                  accountId: 1234
                  data:
                    curp: GOCJ900520HDFRRN04
                    foreignerWithoutCurp: false
                    rfc: GODE561231GR8
                    nif: ASDASFASD12
                    tin: 999-99-9999
                    nss: 12-34-56-7890-1
                    firstName: JUAN
                    middleName: CARLOS
                    firstLastName: GÓMEZ
                    secondLastName: DÍAZ
                    dateOfBirth: 20/05/1990
                    gender: 1
                    nationality: MX
                    countryOfBirth: MX
                    stateOfBirth: CHS
                    cityOfBirth: '1214005'
                    ppe: false
                    bankAreaTypeId: '1'
                    contraTypeId: '1'
                    typeContractSubtypeId: '1'
              privacy-notice:
                value:
                  clientId: 1234
                  sectionId: privacy-notice
                  accountId: 1234
                  data:
                    marketing:
                      marketingConsent: true
                      advertisingConsentActinverGroup: true
                      rejectFinancialOffersFromActinver: true
                    privacyNotice:
                      consentToPrimaryDataProcessing: true
                      consentToSecondaryUse: true
                      consentToMarketingContactAndDataTransfer: true
              spouse-data:
                value:
                  clientId: 1234
                  sectionId: spouse-data
                  accountId: 1234
                  data:
                    spousedata:
                      curp: GOCJ900520HDFRRN04
                      foreignerWithoutCurp: false
                      fiscalId: "1"
                      rfc: GODE561231GR8
                      nif: ASDASFASD12
                      tin: 999-99-9999
                      nss: 12-34-56-7890-1
                      firstName: JUAN
                      middleName: CARLOS
                      firstLastName: GÓMEZ
                      secondLastName: DÍAZ
                      dateOfBirth: 20/05/1990
                      gender: 1
                    workingfields:
                      occupation: 1
                      businessActivity: 1
                    address:
                      addressType: '1'
                      other: ''
                      country: MX
                      federalEntity: CHS
                      postalCode: '06500'
                      city: '1214005'
                      municipality: '001'
                      neighborhood: '1'
                      street: CALLE HIDALGO
                      externalNumber: '25'
                      internalNumber: '1'
              address:
                value:
                  clientId: 1234
                  sectionId: address
                  accountId: 1234
                  data:
                    addressList:
                    - addressType: '1'
                      addressRole: '1'
                      country: MX
                      postalCode: '06500'
                      street: AV. JUÁREZ
                      externalNumber: '10'
                      internalNumber: 3A
                      federalEntity: CHS
                      municipality: '001'
                      neighborhood: '1'
                      city: '1214005'
                      geographicalArea: centro sur
                      deliveryCenter: EJEMPLO
                      timeLiveMexico: un año 10 meses
                      proofOfAddressType: '1'
                      addressProofIssueDate: 01/08/2025
                      expirationYear: 2025
                      reasonsOpeningContractMexico: porque si
                      other: ''
                      taxPostalCode: '06500'
                      isAddressResidenceSameTax: false
              beneficiaries: #BENEFICIARIO
                value:
                  clientId: 1234
                  sectionId: beneficiaries
                  accountId: 1234
                  data:
                    beneficiaries:
                    - curp: PELM950315MDFLRR05
                      foreignWithoutCURP: false
                      rfc: PEL950315ABC
                      nif: ASDASFASD12
                      tin: 999-99-9999
                      nss: 12-34-56-7890-1
                      country: MX # pais de nacimiento
                      firstName: MARÍA
                      middleName: ELENA
                      firstLastName: PÉREZ
                      secondLastName: LÓPEZ
                      dateOfBirth: 15/03/1995 # fecha de nacimiento
                      gender: 1
                      relationship: 1
                      beneficiaryPercentage: '50'
                      maritalStatus: "12" # campo agregado por comentario en correo pero no esta contemplatdo en HU ni Figma
                      nationality: "124" # campo agregado por comentario en correo pero no esta contemplatdo en HU ni Figma
                      federalEntity: "12" # campo agregado por comentario en correo pero no esta contemplatdo en HU ni Figma
                      address:
                        addressType: '1'
                        country: MX
                        street: CALLE HIDALGO
                        externalNumber: '25'
                        internalNumber: '1'
                        postalCode: '06500'
                        federalEntity: CHS
                        municipality: '001'
                        neighborhood: '1'
                        city: '1214005'
              ppe-information:
                value:
                  clientId: 1234
                  sectionId: ppe-information
                  accountId: 1234
                  data:
                    ppeType: NACIONAL
                    positionHeld: EMPLEADO
                    expirationDate: 31/12/2026
                    isPpe: true
                    hasEconomicDependents: true
                    hasAssocioations: true
                    hasFamilyPpe: false
                    economicDependents:
                    - firstName: MARÍA
                      middleName: ELENA
                      firstLastName: PÉREZ
                      secondLastName: LÓPEZ
                      rfc: MXXX809732
                      curp: MXXX809732HDFRNM
                      foreignerWithoutCurp: false         
                      maritalStatus: '1'   
                      occupation: '1'
                      economicActivity: '1' # OBLIGATORIO
                      nif: '' # OBLIGATORIO              
                      tin: '' # OBLIGATORIO             
                      nss: '' # OBLIGATORIO
                      dateOfBirth: 15/12/1980
                      addressType: '1'
                      other: ''
                      country: MX
                      street: CALLE HIDALGO
                      externalNumber: '25'
                      internalNumber: '1'
                      postalCode: '06500'
                      federalEntity: CHS
                      city: '1214005'
                      municipality: '001'
                      neighborhood: '1'
                      relationship: 1
                      nacionality: MX
                      phone: '5544554455'
                    associations:
                    - companyName: ABARRATES LA ESPERANZA
                      rfc: MXXX809732
                      nif: nif # OBLIGATORIO
                      tin: tin # OBLIGATORIO
                      nss: nss # OBLIGATORIO
                      constitutionDate: 12/12/2121 # OBLIGATORIO
                      commercialline: CONSULTORIA
                      economicActivity: '882'
                      administratorName: Carlos Perez Sanchez
                      nacionality: MX
                      addressType: '1'
                      other: ''
                      country: MX
                      street: CALLE HIDALGO
                      externalNumber: '25'
                      internalNumber: '1'
                      postalCode: '06500'
                      federalEntity: CHS
                      city: '1214005'
                      municipality: '001'
                      neighborhood: '1'
                      phone: '5544554455'
                    familyData:
                    - firstName: MARÍA
                      middleName: ELENA
                      firstLastName: PÉREZ
                      secondLastName: LÓPEZ
                      positionHeld: EMPLEADO
                      positionHeldEndDate: 23/08/2000
                      relationship: 1
                      nacionality: MX
                      rfc: MXXX809732
                      nif: nif # OBLIGATORIO
                      tin: tin # OBLIGATORIO
                      nss: nss # OBLIGATORIO
                      curp: MXXX809732HDFRNM
                      foreignerWithoutCurp: false
                      dateOfBirth: 15/12/1980
                      maritalStatus: 1
                      countryOfBirth: MX
                      federalEntity: CHS
                      city: '1214005'
              fiscal-self-declaration: # AUTO-CERTIFICACION Y DATOS FISCALES
                value:
                  clientId: 1234
                  sectionId: fiscal-self-declaration
                  accountId: 1234
                  data:
                    mexicoResident: true
                    curp: GOCJ900520HDFRRN04
                    foreignWithoutCurp: false
                    rfc: GODE561231GR8
                    name: JUAN DIAZ
                    fiscalRegimeId: 12
                    cfdiUse: D06
                    taxPostalCode: '566024'
                    nationality: MX
                    country: MX
                    fiscalResidenceAbroad: true
                    facta: true
                    crs: true
                    fiscalResidences:
                    - personType: 1
                      country: MX
                      declarationFiscalResidence: false
                      proofOfAddressType: '1'
                      issueDate: 02/09/2025
                      expirationStatus: STATUS
                      expirationDate: 02/09/2025
                      certificationDate: 02/09/2025
                      declarationYear: 2025
                      aditionalDays: 1-99
                      factaObligations:
                        autentication: ID FISCAL EXTRANJERO
                        nif: ASDASFASD12
                        tin: 999-99-9999
                        nss: 12-34-56-7890-1
                      activeFiscalDomicilie: true
              signature:
                value:
                  clientId: 1234
                  sectionId: signature
                  accountId: 1234
                  data:
                    signatureType: Solidaria
                    ipabOwnership: 100%
                    isrRetention: 100%
                    coHolders: # Cotitular
                    - curp: PASJ955022HDFRRN04
                      foreignerWithoutCurp: false
                      rfc: PASJ9550223
                      nif: ASDASFASD12
                      tin: 999-99-9999
                      nss: 12-34-56-7890-1
                      firstName: JOAQUIN
                      middleName: ''
                      firstLastName: PACHECO
                      secondLastName: SANTIAGO
                      dateOfBirth: 23/02/1995
                      gender: 2
                      maritalStatus: 1
                      nacionality: 1
                      countryOfBirth: MX
                      federalEntity: 1
                      relationship: 1
                      positionHeld: ''
                      positionHeldEndDate: ''
                      identificationType: 1
                      countryOfIdentification: MX
                      companyName: ''
                      jobTitle: ''
                      signatureType: A
                      IPABCoverage: 50%
                      incomeTaxWithholding: 50%
                      fiscalRegime: PF
                      SATRegisteredName: DANIEL MARTINEZ
                      useCFDI: ''
                      personPpe:
                        isPpe: true
                        ppeType: NACIONAL
                        positionHeld: JEFE DE GOBIERNO
                        positionEndDate: 24/12/2026
                        hasppeRelatives: true
                        ppeRelatives:
                        - curp: PASJ955022HDFRRN04
                          rfc: WQJS12345RTS
                          nif: ASDASFASD12
                          tin: 999-99-9999
                          nss: 12-34-56-7890-1
                          firstName: CESAR
                          middleName: AUGUSTO
                          firstLastName: CAMPIA
                          secondLastName: PEREZ
                          dateOfBirth: 23/02/1995
                          nationality: "AD"
                          relationship: 1
                          positionHeld: JEFE DE GOBIERNO
                          positionEndDate: 24/12/2026
                      identification:
                        - countryOfIdentification: MX
                          identificationType: "1"
                          identificationNumber: 12454HGS
                          expirationDate: 10/10/2026 
                      residentialAddress:
                        addressRol: "1"
                        addressType: "1"
                        other: "otro tipo de direccion"
                        country: MX
                        street: AV. JUÁREZ
                        externalNumber: '10'
                        internalNumber: ''
                        postalCode: '06500'
                        federalEntity: 1
                        city: "ciudad"
                        municipality: 1
                        neighborhood: 1
                        geographicalArea: ''
                        deliveryCenter: ''
                      fiscal-self-declaration:
                        residesInMexico: true
                        SATRegisteredName: "Nombre ante el SAT"
                        fiscalRegime: "21"
                        useCFDI: "23"
                        taxPostalCode: "12345"
                        isForeignTaxResident: true
                        taxAddress:
                          - taxAddress:
                              personType: "1"
                              fiscalResidence: "MX"
                              selfCertification: true
                              proofOfTaxResidency: "011"
                              certificationDate: 28/10/2025
                              declarationYear: 2025
                            fatcaCompliance:
                              autentication: "01"
                              nif: ASDASFASD12
                              tin: 999-99-9999
                              nss: 12-34-56-7890-1
                            taxAddressActive: true
                      contactData:
                        DataNonDisclosureLetter: false
                        registeredPhones:
                        - type: 1
                          country: MX
                          areaCode: '52'
                          phone: '5545319245'
                          extension: '7812'
                          notificationPhone: true
                        registeredEmails:
                        - emailAddress: DANIEL.MARTINEZ@CORREO.COM
                          notificationEmail: true
                    legalProxy: # Apoderado
                    - curp: LUPJ880512HDFRRN04
                      foreignerWithoutCurp: false
                      rfc: LUPJ8805123
                      nif: ASDASFASD12
                      tin: 999-99-9999
                      nss: 12-34-56-7890-1
                      firstName: LUIS
                      middleName: PABLO
                      firstLastName: LÓPEZ
                      secondLastName: SANTIAGO
                      dateOfBirth: 23/02/19995
                      gender: 2
                      maritalStatus: 1
                      nacionality: 1
                      countryOfBirth: MX
                      federalEntity: 1
                      identificationType: 1
                      countryOfIdentification: MX
                      nifTinNss: MADA81052
                      economicActivity: 1
                      occupation: 1
                      profession: 1
                      companyName: ''
                      jobTitle: ''
                      email: correo@personal.com
                      personPpe:
                        isPpe: true
                        ppeType: NACIONAL
                        positionHeld: JEFE DE GOBIERNO
                        positionEndDate: 24/12/2026
                        hasppeRelatives: true
                        ppeRelatives:
                        - curp: LUPJ880512HDFRRN04
                          rfc: WQJS12345RTS
                          nif: ASDASFASD12
                          tin: 999-99-9999
                          nss: 12-34-56-7890-1
                          firstName: CESAR
                          middleName: JULIAN
                          firstLastName: CAMPIA
                          secondLastName: REYES
                          dateOfBirth: 23/02/1995
                          nationality: "AD"
                          relationship: 1
                          positionHeld: JEFE DE GOBIERNO
                          positionEndDate: 24/12/2026
                      identification:
                        - countryOfIdentification: MX
                          identificationType: "1"
                          identificationNumber: 12454HGS
                          expirationDate: 10/10/2026 
                      residentialAddress:
                        addressRol: "12"
                        addressType: "1"
                        other: "otro"
                        country: MX
                        street: AV. JUÁREZ
                        externalNumber: '10'
                        internalNumber: ''
                        postalCode: '06500'
                        federalEntity: 1
                        municipality: 1
                        neighborhood: 1
                        geographicalArea: '' # si puede enviarse vacio
                        deliveryCenter: '' # si puede enviarse vacio
                      contactData:
                        DataNonDisclosureLetter: false
                        registeredPhones:
                        - type: 1
                          country: MX
                          areaCode: '52'
                          phone: '5545319245'
                          extension: '7812'
                          notificationPhone: true
                        registeredEmails:
                        - emailAddress: DANIEL.MARTINEZ@CORREO.COM
                          notificationEmail: true
                      faculties:
                        faculties: false
                        domain: false
                        delegationPower: false
                        creditInstruments: false
                        powerToOpenAccounts: false
                        numberPropertyDeeds: ''
                        datePropertyDeeds: 18/02/1998
                        notaryName: ''
                        notarynumber: 0
                        protocolizationBranch: ''
                        limitationsOnAuthority: ''
              general-information: #  Datos Generales Cliente
                value:
                  clientId: 1234
                  sectionId: general-information
                  accountId: 1234
                  data:
                    personClassification: EMPLEADO # OBLIGATORIO
                    economicActivity: '882' # OBLIGATORIO
                    maritalStatus: 1 # OBLIGATORIO
                    marriageType: 1 # OBLIGATORIO
                    sector: '01' # OBLIGATORIO
                    actinverEmployee: true # OBLIGATORIO
                    employeeNumber: '98765'
                    occupation: '1'
                    profession: INGENIERO EN SISTEMAS
                    companyName: TECNOLOGÍAS XYZ
                    jobTitle: DESARROLLADOR SR.
                    companyPhone: '5544332211'
                    country: MX # OBLIGATORIO
                    street: CALLE REFORMA # OBLIGATORIO
                    externalNumber: '123' # OBLIGATORIO
                    internalNumber: 2B
                    postalCode: '06500' # OBLIGATORIO
                    federalEntity: CHS # OBLIGATORIO
                    city: '1214005' # OBLIGATORIO
                    municipality: '001' # OBLIGATORIO
                    website: HTTPS://WWW.EJEMPLO.COM # OBLIGATORIO
                    related: true # OBLIGATORIO
                    relationship: 1
                    institutionName: BBVA
                    fiel: ABCD123456XYZ
                    fielExpirationDate: 31/12/2027 # OBLIGATORIO
                    banxicoAuthorization: true
                    nonGuaranteedByIPAB: CLAVE IPAB
                    acting: true # OBLIGATORIO
                    hasSupplier: false # OBLIGATORIO
                    operatesChanges: false # OBLIGATORIO
                    addressType: '1' # OBLIGATORIO
                    neighborhood: '1' # OBLIGATORIO
                    websiteCompany: 'WWW:EJEMPLO:COM:'
                    incapacity: false # Otros --> Invalidez o incapacidad
                    disabilityJustification: false # Otros --> Carta de justificacion de invalidez
                    dateOfDeath: '20/05/1990' # otros --> fecha de defunción
                    contractData:
                      customerStatus: 'Estatus de cliente' # Estatus de cliente
                      applicationStatus: 'Aprobada' #Estatus de la solicitud
                      openingDate: 31/12/2028 # Fecha de apertura
                      initialRiskScore: 10 # Riesgo inicial- Puntación
                      initialRiskDescription: 'Riesgo inicial- Descripción'  # Riesgo inicial- Descripción
                      modifiedRiskScore: 5 # Riesgo Modificado - Puntuación
                      modifiedRiskDescription: 'Riesgo Modificado - Descripción'  # Riesgo Modificado - Descripción
                      origin: 'Origen' # Origen
                      upgradeDateN4: 31/12/2028 # Fecha upgrade a N4
                      numbered: false # Es numerado
                      operatesCapital: false # opera capitales
                      checkProtection: true # Protección de cheques
                      properPosition: false  #Es posición Propia
                      socialSecurity: false # Previsión social
                      biometricsAccount: false # Cuenta con biometricos
                      facialBiometrics: false # Cuenta con Biométrico Facial
                      enrollmentStatus: 'Estatus de enrolamiento' # estatus enrolamiento
                      associateDirector: 'Director Asociado' # Director asociado
                      directPromoter: 'Promotor directo' # Promotor directo
                      financialCenter: 'Centro financiero' #Centro financiero
                      withholdingTax: '10' # % retención de ISR
                      creditSuisseCommission: '10' # % de comisión mensual credit suisse
                      commissionPercentage: '20' # Porcentaje de comisión
                      legalEntityIGuarantor: false # La Persona Moral es Afianzadora
                      brokerageHouse: false # Es casa de bolsa
                      authorizationConsultCreditReports: false # Autorización de Consulta de Buró
                    accountManagement: # Manejo de cuenta
                      externalCustody: false # Custodia Externa
                      custody: null # Custodia
                      indevalAccount: null # Cuenta indeval
                      financialCenterDelivery: 'Centro Financiero Responsable de la Entrega' # Centro Financiero Responsable de la Entrega
                      contractManagement: 'Manejo de Contrato' # Manejo de Contrato
                      managementType: 'Tipo de Gestión' # Tipo de Gestión
                      vip: false # VIP
                    generalInformation: # Informacion general
                      reasonOperations: 'Motivo de Operaciones' # Motivo de operaciones
                      otherReasonOperations: 'Otro motivo de Operación' #Otro motivo de Operación
                      confirmationAuthorized: 'Medio por el cual se autoriza la confirmación de operaciones y/o instruccione' #Medio por el cual se autoriza la confirmación de operaciones y/o instruccione
                      referringProduct: # Producto preferente
                        documents: false # Documentos
                        transfers: false # Transferencia
                        depositInAccount: false # Deposito en cuenta
                        other: false # otro
                        SpecifyPreferredProduct: null # Especifica el Producto Preferente Otro
                    associateDirector: # Director asociado
                      directorStatus: 'Estatus' #estatus de director asociado
                      associateDirectorFolio: 'Folio Director Asociado' #Folio Director Asociado
                      advisorNumber: 11 #No. Asesor
                      name: 'Nombre director asociado' #Nombre director asociado
                    geolocation: # Geolocalización
                      geolocationConsent: false # Consentimiento de  Geolocalización
                      date: 31/12/2028 # Fecha
                      hour: '09:30' # Hora
                      latitude: '19° 26 Norte(N)' # Latitud
                      longitude: '99° 08 Oeste (O)'  # Longitud
              authorized-person: # Persona autorixada
                value:
                  clientId: 1234
                  sectionId: authorized-person
                  accountId: 1234
                  data:
                    authorizedPerson:
                    - curp: PAGS90223JHMCGNQ08
                      foreignWithoutCURP: false
                      rfc: PAGS90223
                      firstName: JOAQUIN
                      middleName: SEGUNDO
                      lastName: PACHECO
                      secondLastName: SANTIAGO
                      birthDate: 23/02/1995
                      gender: 1
                      maritalStatus: 1
                      nationality: MX
                      birthCountry: MX
                      federalEntity: '1'
                      signatureClass: A
                      checkbookManagementAccess: true
                      relationship: '1'
                      economicActivity: '1'
                      occupation: '1'
                      companyName: ''
                      jobTitle: ''
                    personPpe:
                      isPpe: true
                      ppeType: NACIONAL
                      positionHeld: JEFE DE GOBIERNO
                      positionEndDate: 24/12/2026
                      hasppeRelatives: true
                      ppeRelatives:
                      - rfc: WQJS12345RTS
                        firstName: CESAR
                        firstLastName: CAMPIA
                        relationship: 1
                        positionHeld: JEFE DE GOBIERNO
                        positionEndDate: 24/12/2026
                    residenceAddress:
                    - addressType: 1
                      otherAddressType: OTRO TIPO
                      country: MX
                      street: JOSE A TORRES
                      externalNumber: '1234'
                      internalNumber: B-12
                      postalCode: '06500'
                      federalEntity: 1
                      municipality: '001'
                      neighborhood: PAULINO NAVARRO
                    contact:
                    - type: CASA
                      country: MX
                      areaCode: '52'
                      phone: '5534923794'
                      extension: '7812'
                      emailAddress: CORREO@PERSONAL.COM
                    faculties:
                      signatureInstruction: 1 FIRMA A
                      otherSignatureInstruction: ''
              personal-interview:
                value:
                  clientId: 1234
                  sectionId: personal-interview
                  accountId: 1234
                  data:
                    date: 02/09/2025
                    interviewee: JUAN PEREZ
                    opening: Presencial
                    interviewLocation: Otro Domicilio
                    otherLocation: Domicilio
                    question1: true
                    question2: true
                    atypicalSituation: Prestanombres
                    question3: true
                    residence: Mexico
                    geographicalArea: Cerca del Centro Financiero
                    homeVisit: false
                    reason: NO ES CERCA
                    locality: Localidad ingresada
                    addressType: 1
                    matchingAddress: true
                    ObservationsHomeVisit: Razones
                    customerKnowledge: Lo conozco de mucho tiempo
                    time: 3 meses
                    clientNumber: 24543
                    clientInvestmentAmount: No coincide con su nivel socioeconómico
                    initialInvestment: Transferencias internacionales
                    country: MX
                    moreInformationClient: Informacion
                    isPFWithBusinessActivity: true
                    lowRisk:
                      companyName: EMPRESA
                      jobTitle: PUESTO
                      timeWorking: 3 meses
                    mediumRisk:
                      initialInvestmentInActinver: Otras cuentas bancarias a su nombre
                      relationship: 3
                      justificationInitialInvestment: true
                    highRisk:
                      productsOffered: PRODUCTOS OFRECIDOS
                      inventory: true
              bank-account: # cuenta bancaria
                value:
                  clientId: 1234567890
                  sectionId: bank-account
                  accountId: 1234
                  data:
                    bankAccounts:
                    - accountType: '1'
                      currency: '1'
                      domiciledIn: MX
                      accountStatus: '2'
                      isThirdParty: false
                      paymentMethodDocument: false
                      paymentMethodElectronic: true
                      maxAmount: '100000'
                      bank: '28710'
                      alias: ALIAS CUENTA
                      beneficiaries:
                      - beneficiaryName: '1'
                        curp: PASJ955022HDFRRN04
                        rfc: PELM950315XXX
                        accountNumberIban: 00012345678901234567
                        clabe: '012345678901234567'
                      - beneficiaryName: '2'
                        curp: PASJ955022HDFRRN04
                        rfc: PELM950315XXX
                        accountNumberIban: 00098765432109876543
                        clabe: '765432109876543210'
                      reference: REFERENCIA XYZ
                      concept: CONCEPTO EJEMPLO
                      intermediaryBank: BANCO INTERMEDIARIO EJEMPLO
                      subaccountHolder: TITULAR SUBACCOUNT EJEMPLO
                      subaccountKey: CLAVE SUBACCOUNT
              real-owner: # propietario real
                value:
                  clientId: 1234
                  sectionId: real-owner
                  accountId: 1234
                  data:
                    generalData:
                      foreignWithoutCURP: false
                      curp: PELM950315MDFLRR05
                      rfc: PELM950315XXX
                      nif: 
                      tin: 
                      nss:
                      firstName: PEDRO
                      middleName: ELENA
                      firstLastName: LÓPEZ
                      secondLastName: MARTÍNEZ
                      dateOfBirth: 15/03/1995
                      gender: 1
                      nacionality: MX
                      countryOfBirth: MX
                      federalEntity: CHS
                      relationship: 1
                      economicActivity: '882'
                      fiel: ABCD123456XYZ
                      fielExpirationDate: 31/12/2027
                      phone: 5544332211
                      email: PEDRO.LOPEZ@CORREO.COM
                    personPpe:
                        isPpe: true
                        ppeType: NACIONAL
                        positionHeld: JEFE DE GOBIERNO
                        positionEndDate: 24/12/2026
                        hasppeRelatives: true
                        ppeRelatives:
                        - curp: GOCJ900520HDFRRN04
                          foreignerWithoutCurp: false
                          rfc: WQJS12345RTS
                          nif: 
                          tin: 
                          nss:
                          firstName: CESAR
                          middleName: "FELIPE"
                          firstLastName: CAMPIA
                          secondLastName: "NUNEZ"
                          nationality: "01"
                          countryOfBirth: "MX"
                          federalEntity: "MX" # OBLIGATORIO
                          relationship: 1
                          positionHeld: JEFE DE GOBIERNO
                          positionEndDate: 24/12/2026
                    addressRealOwner:
                      addressType: '1'
                      other: ''
                      country: MX
                      postalCode: 06500
                      federalEntity: CHS
                      city: '1214005'
                      municipality: '001'
                      neighborhood: 1
                      street: AV. JUÁREZ
                      externalNumber: 10
                      internalNumber: 3A
              resource-provider: # provedor de recursos
                value:
                  clientId: 1234
                  sectionId: resource-provider
                  accountId: 1234
                  data:
                    generalData:
                      personType: '1'
                      curp: GOCJ900520HDFRRN04
                      foreignerWithoutCurp: false
                      rfc: GODE561231GR8
                      nif:
                      tin:
                      nss:
                      firstName: JUAN
                      middleName: CARLOS
                      firstLastName: GÓMEZ
                      secondLastName: DÍAZ
                      dateOfBirth: 20/05/1990
                      gender: 1
                      nacionality: MX
                      countryOfBirth: MX
                      federalEntity: CHS
                      relationship: 1
                      economicActivity: '882'
                      fiel: ABCD123456XYZ
                      expirationFielDate: 10/25/1690
                      phone: '55551234'
                      email: JUAN.PEREZ@CORREO.COM
                    personPpe:
                        isPpe: true
                        ppeType: NACIONAL
                        positionHeld: JEFE DE GOBIERNO
                        positionEndDate: 24/12/2026
                        hasppeRelatives: true
                        ppeRelatives:
                        - curp: GOCJ900520HDFRRN04
                          foreignerWithoutCurp: false
                          rfc: WQJS12345RTS
                          nif: 
                          tin: 
                          nss:
                          firstName: CESAR
                          middleName: "FELIPE"
                          firstLastName: CAMPIA
                          secondLastName: "NUNEZ"
                          nationality: "01"
                          countryOfBirth: "MX"
                          city: "01"  # OBLIGATORIO
                          relationship: 1
                          positionHeld: JEFE DE GOBIERNO
                          positionEndDate: 24/12/2026
                    resourceProviderAddress:
                      addressType: '1'
                      other: ''
                      country: MX
                      postalCode: '06500'
                      federalEntity: CHS
                      city: '1214005'
                      municipality: '001'
                      neighborhood: '1'
                      street: AV. JUÁREZ
                      externalNumber: '10'
                      internalNumber: 3A
      responses:
        '201':
          description: Checkpoint created or updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  applicationNumber:
                    type: string
                    example: '1234567890'
                  sectionId:
                    type: string
                    example: datos-iniciales
                  status:
                    type: string
                    example: CREATED
              examples:
                bank-account:
                  value:
                    applicationNumber: '1234567890'
                    sectionId: bank-account
                    status: CREATED
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: JWT is expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                status: 401
                appCode: CROSS-SUPPORT-E-401
                messages:
                - JWT IS EXPIRED
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                status: 403
                appCode: CROSS-SUPPORT-E-403
                messages:
                - FORBIDDEN
        '404':
          description: Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                status: 404
                appCode: CROSS-SUPPORT-E-404
                messages:
                - RESOURCE NOT FOUND
        '412':
          description: Precondition failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                status: 412
                appCode: CROSS-SUPPORT-E-412
                messages:
                - PRECONDITION FAILED
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                status: 500
                appCode: SPINE-MS_CROSS_SUPPORT-CATALOGS-500
                messages:
                - ERROR EN EL TRATAMIENTO DE SERVICIO WEB; MÁS DETALLES EN LOG DE
                  ERROR DE SERVICIO WEB EN LA PÁGINA DE PROVEEDOR (CRONOMARCADOR UTC
                  20220816151711; ID DE TRANSACCIÓN B742632CC2C200A0E0062ED2ACC62E94)
components:
  schemas:
    errorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 400
        appCode:
          type: string
          example: CROSS-SUPPORT-E-400
        messages:
          type: array
          items:
            type: string
          example:
          - Invalid search parameters
    checkpointRequest:
      type: object
      required:
      - sectionId
      - data
      properties:
        onboardingId:
          type: integer
          format: int64
          example: 1234567890
          description: Unique identifier for the onboarding process
        sectionId:
          type: string
          enum:
          - datos-iniciales
          - identificacion-contacto
          - informacion-ppe
          - datos-generales
          - domicilio
          - firma
          - beneficiarios
          - authorized-person
          - autocertificacion-fiscales
          - entrevista-personal
          description: Tab ID for the checkpoint
        data:
          type: object
          description: Specific data for the tab (variable structure depending on
            tabId)
          additionalProperties: true
        clientId:
          type: string
          description: Client identifier
      description: Request object for checkpoint data
 